### PR TITLE
ADT Explorer bugfixes and updates

### LINKED ISSUE #178: manifest.json referencing "favicon.ico" which is missing, it should be "favicon.png" instead
According to content of "public" folder, there is no "favicon.ico" file which is referenced in manifest.json,
but there is a "favicon.png" available, and also it is referenced in "index.html".

So please update manifest.json to match the proper "favicon.png" reference.

### LINKED ISSUE #182: Model graph shows inheritances to parent, parent's parent, etc
In this scenario, "->" means "extends":
> Neighborhood -> Administrative Area -> Feature -> Spatial Object

But there are inheritance lines from Neighborhood to each of the nodes up the stack...
image

### LINKED ISSUE #198: Model graph shows redundant parent's Components link
In a similar way to #182 , the parent's (and parent's parent's,...) Component links are duplicated into any `extends` children in the Model graph view.

Given the following DTDL:
```
[
  {
    "@context": "dtmi:dtdl:context;2",
    "@id": "dtmi:Parent;1",
    "@type": "Interface",
    "contents": [
      {
        "@type": "Component",
        "name": "Comp",
        "schema": "dtmi:Component;1"
      }
    ],
    "displayName": "Parent"
  },
  {
    "@context": "dtmi:dtdl:context;2",
    "@id": "dtmi:Child;1",
    "@type": "Interface",
    "displayName": "Child",
    "extends": "dtmi:Parent;1"
  },
  {
    "@context": "dtmi:dtdl:context;2",
    "@id": "dtmi:Component;1",
    "@type": "Interface",
    "displayName": "Component"
  }
]
```

I get the following Model graph view, with the Component link `Comp` between `Child` and `Component`" being redundant.

Screenshot_20210802_104520

### LINKED ISSUE #226: Hover pop-up for twin shows description from top level extended model
If a model (B) extends another model (A), when you hover over a twin of model B it shows the description from model A. If a model (C) extends model B then it will still show the description for model A. Please see screenshots showing a concrete example where model "orchard" extends "addressable" which extends "geolocatable", hovering over an orchard twin shows the description from the geolocatable model.
Capture_ADTE_twin_description_wrong_model
Capture_ADTE_twin_description_wrong_model_info
Capture_ADTE_twin_description_wrong_model_info_addressable
Capture_ADTE_twin_description_wrong_model_info_geolocatable

### LINKED ISSUE #228: [Bug] Refresh model doesn't work
Minor issue and only cosmetics:
The refresh button on the left pane does not update the model list.
image

### PR DESCRIPTION
**Pull request by ccrowley96**
## ADO listed Bug fixes

- Fixes REST error when landing in explorer for the first time.  Users can no longer cancel out of the ADT URL picker dialogue before selecting an instance URL.  Also removed the call to query models on initial load when no URL is selected. ([ADO item](https://msazure.visualstudio.com/One/_backlogs/backlog/ADT%20ExACT/Epics/?workitem=10277373))
- Model Graph inheritance lines no longer display implied inheritance.  Added logic to slice only the first base model when drawing inheritance lines on the model graph. ([ADO item](https://msazure.visualstudio.com/One/_backlogs/backlog/ADT%20ExACT/Epics/?workitem=10321579))
- Updated model graph 'Run Layout' button to 'Choose layout' with correct icon. ([ADO item](https://msazure.visualstudio.com/One/_backlogs/backlog/ADT%20ExACT/Epics/?workitem=10451273))
- Fixed bug where model refresh button did nothing.  This was happening when caching was enabled.  The cached models would be hit and no refresh was executed.  These changes add a forced cache bypass to this button - forcing a refresh. ([ADO item](https://msazure.visualstudio.com/One/_backlogs/backlog/ADT%20ExACT/Epics/?workitem=10744451))
- Fixed issue where clicking 'Run query' from the model graph had no effect and was confusing to users.  Now, when a user runs a query from the model graph, it snaps back to the twin graph and executes the query. ([ADO item](https://msazure.visualstudio.com/One/_backlogs/backlog/ADT%20ExACT/Epics/?workitem=10919172))
- Fixed issue where ADT URL configuration was not saving when local storage cleared.  URL configuration is now also stored in app state and only seeded by local storage - this should fix the multi-tab configuration issue users are facing. ([ADO item](https://msazure.visualstudio.com/One/_backlogs/backlog/ADT%20ExACT/Epics/?workitem=12454936))
- Updated caching to default OFF ([ADO item](https://msazure.visualstudio.com/One/_backlogs/backlog/ADT%20ExACT/Epics/?workitem=12390560))

### Before
image

### After
image

## GitHub issue bug fixes
- fixes #228
- fixes #226
- fixes #198
- fixes #182
- fixes #178

### Model upload confirmation

Added model upload confirmation message bar and info dialogue.  Clicking view details on the success message bar opens the dialogue showing the details of the uploaded models.  The success message bar dismisses after 15 seconds.

image

## Visual changes
Updated panel tabs to Fluent style with lighter background.  This helps to clarify what tab is selected and makes their tab nature more apparent.

image

Fixed high-contrast mode toggle UI.

### Before

image

### After

image

### CODE REVIEW

File: client/src/components/ModelGraphViewerComponent/ModelGraphViewerComponent.js [hunk 1]
```diff
@@ -188,7 +188,7 @@ class ModelGraphViewerComponent extends React.Component {
 
   getExtendRelationships = list =>
     list.flatMap(m =>
-      m.bases.map(b => ({
+      m.bases.slice(0, 1).map(b => ({
```
Comment (niusoff) [inline client/src/components/ModelGraphViewerComponent/ModelGraphViewerComponent.js:191]: not sure how I feel about a slice guaranteed to be length one into a map, but I guess I'll let it slide this arr.slice(0,1).length time...

File: client/src/services/ConfigService.js [hunk 2]
```diff
@@ -3,34 +3,37 @@
...
+    this._config = config;
+    storageService.setLocalStorageObject(StorageKeyName, config);
+    eventService.publishClearCache();
   }
 
-  getConfig(force) {
-    const config = storageService.getLocalStorageObject(StorageKeyName);
-    if (config && !force) {
-      return config;
+  getConfig() {
```
Comment (niusoff) [inline client/src/services/ConfigService.js:21]: Not sure how I feel about this - I guess it's fine since using an await results in a non promise return getting wrapped in a promise and then immediately resolved, but it does feel weird to me to have the possibility of return of either an object or a promise

**Review by niusoff — APPROVED** [review]
Overall looks great! The one thing I noticed when playing around with it is an accessibility bug that appears to be present in prod as well, so, it's not a regression - there appears to be some issues with tabbing into/out of the "twin graph" and "model graph" tab buttons. Can repro by clicking on one of them, hitting tab, then shift tab and you can see the focus jump from the "model graph" button to the previous thing in the tab order. Not sure what's triggering this

File: client/src/components/ModelGraphViewerComponent/ModelGraphViewerComponent.js (hunk 1 above)
Comment (ccrowley96) [reply client/src/components/ModelGraphViewerComponent/ModelGraphViewerComponent.js:191]: hahaha good call.  I actually found another issue here.  

This was only showing the first extended model, but there can be a case where:

Model A extends [Model B, Model C]
Model B extends Model D

Before, the red line to C wasn't showing.

image

I added another array to the model object which only contains the extended models defined **on** the root model (not all extended models aggregated from all bases).

```js
getExtendRelationships = list =>
  list.flatMap(m =>
    m.rootBases.map(b => ({
      sourceId: m.id,
      targetId: b,
      relationshipName: "Extends",
      relationshipId: "extends"
    }))
  );
```

File: client/src/services/ConfigService.js (hunk 2 above)
Comment (ccrowley96) [reply client/src/services/ConfigService.js:21]: Good call, that is weird.  I'm adding `Promise.resolve` to wrap those objects so every path returns a promise!

**Comment by ccrowley96** [comment]
> Overall looks great! The one thing I noticed when playing around with it is an accessibility bug that appears to be present in prod as well, so, it's not a regression - there appears to be some issues with tabbing into/out of the "twin graph" and "model graph" tab buttons. Can repro by clicking on one of them, hitting tab, then shift tab and you can see the focus jump from the "model graph" button to the previous thing in the tab order. Not sure what's triggering this

I think the Fluent UI Pivot Items (tabs) and command bars use arrow keys to navigate within their tab group rather than tab / shift tab.  So this might not be a bug, not positive I'm reproing what you hit though.
